# Generated by Django 5.2.16 on 2026-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=20)),
                ('target_stock', models.IntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
