# Generated by Django 5.2.16 on 2026-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['sku'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
